# Hugging face spaces (CPU) でエディタ (server_editor.py) のデプロイ用

# See https://huggingface.co/docs/hub/spaces-sdks-docker-first-demo

FROM python:3.10

RUN useradd -m -u 1000 user

USER user

ENV HOME=/home/user \
    PATH=/home/user/.local/bin:$PATH

WORKDIR $HOME/app

RUN pip install --no-cache-dir --upgrade pip

COPY --chown=user . $HOME/app

RUN pip install --no-cache-dir -r $HOME/app/requirements.txt

CMD ["python", "server_editor.py"]
